# Generated by Django 4.1.7 on 2023-02-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023)),
                ('course', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Bachelor'), (2, 'Master'), (3, 'Reduced')])),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(1, 'Teacher'), (2, 'Student')])),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.group')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('dayofweek', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('weekfrequency', models.IntegerField(choices=[(1, 'Each Week'), (2, 'Each Two Weeks')], default=1)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('meetingurl', models.URLField()),
                ('location', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Lecture'), (2, 'Practice')])),
                ('courseurl', models.URLField()),
                ('groups', models.ManyToManyField(to='main.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
    ]
