# Generated by Django 4.1.7 on 2023-02-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='Groups',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='Lessons',
        ),
        migrations.AlterModelTable(
            name='person',
            table='Persons',
        ),
    ]
