# Generated by Django 4.1.7 on 2023-02-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_group_table_alter_lesson_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table='Faculties',
        ),
    ]
