# Generated by Django 4.1.7 on 2023-02-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_lesson_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('firstweeknumber', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
    ]
