# Generated by Django 4.1.7 on 2023-02-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_semester_remove_group_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='firstweeknumber',
        ),
        migrations.AddField(
            model_name='semester',
            name='weektype',
            field=models.IntegerField(choices=[(2, 'Numerator'), (3, 'Denominator')], default=3),
            preserve_default=False,
        ),
    ]
